include(CMakeParseArguments)

function(define_config_option)
    set(options REQUIRED)
    set(oneValueArgs NAME TYPE DEFAULT DESCRIPTION)
    set(multiValueArgs OPTIONS RANGE)
    cmake_parse_arguments(CONFIG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    set(CACHE_TYPE "STRING")
    if(CONFIG_TYPE STREQUAL "BOOL")
        set(CACHE_TYPE "BOOL")
    elseif(CONFIG_TYPE STREQUAL "INTEGER")
        set(CACHE_TYPE "STRING")
    elseif(CONFIG_TYPE STREQUAL "STRING")
        set(CACHE_TYPE "STRING")
    endif()

    if(NOT DEFINED ${CONFIG_NAME})
        if(DEFINED CONFIG_DEFAULT)
            set(${CONFIG_NAME} ${CONFIG_DEFAULT} CACHE ${CACHE_TYPE} ${CONFIG_DESCRIPTION})
        else()
            set(${CONFIG_NAME} "" CACHE ${CACHE_TYPE} ${CONFIG_DESCRIPTION})
        endif()
    endif()

    if(CONFIG_REQUIRED AND "${${CONFIG_NAME}}" STREQUAL "")
        message(FATAL_ERROR "${CONFIG_NAME} cannot be empty")
    endif()

    if(CONFIG_OPTIONS)
        list(JOIN CONFIG_OPTIONS "|" valid_options)
        if(NOT ${CONFIG_NAME} IN_LIST CONFIG_OPTIONS)
            message(FATAL_ERROR "Invalid ${CONFIG_NAME} '${${CONFIG_NAME}}'. Valid options: ${valid_options}")
        endif()
    endif()

    if(CONFIG_RANGE)
        list(GET CONFIG_RANGE 0 range_start)
        list(GET CONFIG_RANGE 1 range_end)
        if(NOT (${CONFIG_NAME} GREATER_EQUAL range_start AND ${CONFIG_NAME} LESS_EQUAL range_end))
            message(FATAL_ERROR "Invalid ${CONFIG_NAME} '${${CONFIG_NAME}}'. Must be between ${range_start} and ${range_end}.")
        endif()
    endif()

    if(${CONFIG_TYPE} STREQUAL "BOOL")
        if(${${CONFIG_NAME}})
            set(${CONFIG_NAME} 1 PARENT_SCOPE)
        else()
            set(${CONFIG_NAME} 0 PARENT_SCOPE)
        endif()
    else()
        set(${CONFIG_NAME} ${${CONFIG_NAME}} PARENT_SCOPE)
    endif()
endfunction()
